### PR TITLE
Fix incorrect error when dealing with rails blocks in some cases

### LINKED ISSUE #36: Incorrect error
This produces an error:

captura de ecra de 2016-04-05 11 08 06

It says "Unexpected ')'", however the code works fine in practice.

Running `cat [my file].erb | erb -x | ruby -c` reveals that:

```
-:15: syntax error, unexpected ')'
      ) do |f| ).to_s); _erbout.concat "\n"
                ^
-:33: syntax error, unexpected end-of-input, expecting ')'
```

### Further investigation

It seems that the issue is caused by a hack implemented by the [Rails ERB handler](https://github.com/rails/rails/blob/9d6e502f81bcf56c7da8a7d1f9e433b4e0a7e3e9/actionpack/lib/action_view/template/handlers/erb.rb#L32) that allows using `<%=` to output what would be invalid ERB syntax, since ERB requires code inside `<%= %>` to be a complete expression that could stand on its own, and obviously `form_for foo do` doesn't stand on its own.

More info in [this blog post](http://timelessrepo.com/block-helpers-in-rails3) and [this stackoverflow question](http://stackoverflow.com/questions/17374274/why-is-this-an-error-with-erb).

In syntastic the problem was worked around by replacing all occurrences of `<%=` with `<%` before passing the text to `erb -x` for compiling, as can be seen [in this commit](https://github.com/scrooloose/syntastic/commit/0f1d451d96970de4b1f07290f6231f9411749919).

### Solution

I'm going to fix this by replacing the current regex based implementation with the same solution that the syntastic project used, since it's much more straightforward, less likely to break something, more accommodating to different ways of writing the block syntax and in practice it shouldn't introduce any errors in the parsed output.

### PR DESCRIPTION
**Pull request by ricardograca**
If a rails helper function that accepts blocks was written in a way to have newlines in between arguments, that expression would be marked as an error when it is in fact valid syntax. Example:

    <%= form_for(
      something
    ) do %>
    <% end %>

This syntax is in fact incorrect ERB, so the linter is correct in marking it as an error, but Rails allows it and produces the expected result.

The problem in `linter-erb` was caused by the regex used to capture that case not being written in a way to handle newlines. Instead of trying to edit the regex to handle all possible use cases a much more simple solution was used. All `<%=` occurrences will simply be replaced by `<%` before being passed to the external linter, and that prevents any errors from being detected. This is the same solution used by other projects, e.g. [syntastic](https://github.com/scrooloose/syntastic/commit/0f1d451d96970de4b1f07290f6231f9411749919).

Fixes #36.

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -74,17 +74,10 @@ export default {
 
         // Call ERB to "de-templatize" the code
         return helpers.exec(this.erbPath, erbArgs,
-          { stdin: text, cwd: fileDir }
+          { stdin: text.replace(/<%=/g, '<%'), cwd: fileDir }
```
Comment (Arcanemagus) [inline lib/index.js]: Should this replacement be limited to only Ruby (`text.html.erb` scope) files like the previous method was?

Comment (ricardograca) [inline lib/index.js]: I thought the erb linter was only called when the user was editing a `.erb` file in which case I guess everything in that file is in the `text.html.erb` scope. Isn't that the case?

Comment (Arcanemagus) [inline lib/index.js]: Sorry, looks like the check was a _negative_ check there, `text.html.erb` is a regular ERB file, `text.html.ruby` is apparently the scope of a Rails file.

Before the modification was only being done if the scope _wasn't_ `text.html.erb` (and thus must have been `text.html.ruby`), now this modification is being done on every file.

This may be a harmless modification, I just wanted to make sure that if that text is something legitimately wrong with _non_-Rails files that it is still caught.

Comment (ricardograca) [inline lib/index.js]: Right, good call. I thought the rails scope was also `text.html.erb`. Are you sure in the case of rails it's being detected as `text.html.ruby`? The bottom right indicator says "HTML (Ruby - ERB)" and I see no other ERB scope in the list. In fact, how would Atom tell Rails ERB from regular ERB? Extension is the same and the tags are the same. The only difference is that Rails ERB supports writing an incomplete expression inside `<$= %>` and regular ERB doesn't.

Comment (Arcanemagus) [inline lib/index.js]: I'm not sure, I'll refer back to the "I don't use Ruby" as to why :stuck_out_tongue:

I just know that this package claims to understand `text.html.erb` and `text.html.ruby` scopes, and previously it would only modify the output if the file was marked as the `text.html.ruby` scope.

Comment (ricardograca) [inline lib/index.js]: I just checked and there is another scope called "HTML (Rails)" but in all the ERB files that I have in my project it wasn't used. It's always "HTML (Ruby - ERB)" which I suppose is `text.html.erb`. Oh, and the previous check would always pass `text.html.erb` scopes to the replacement function. I personally use this: `if (scopes.indexOf('text.html.erb') > -1)` which for me is easier to read then using the not equals.

The only problem is that this invalid regular ERB code would not raise an error:

```erb
<%= something or_other do %>
<% end %>
```

But, including the `if (scopes.indexOf('text.html.erb') !== -1) {` line wouldn't help anyway since it seems that the scope is always `text.html.erb`, so it always gets passed. For that to work only on rails ERB it would be required that Atom identified rails ERB files as such.

So, there's nothing to do here. If some user of regular ERB complains about the missing error we'll revisit this, but it requires changes outside of `linter-erb`.

Comment (Arcanemagus) [inline lib/index.js]: I believe the other scope comes from a different language package which you may not have installed? Not sure though.

If the replacement causes no issues with regular files, and doesn't prevent any errors from being caught then it shouldn't be an issue leaving it in.

Comment (ricardograca) [inline lib/index.js]: I already looked at the original commit where that extra scope was introduced and it hints at rails ERB being marked as `text.html.ruby`, but I don't think that's the case anymore. The original code would specifically look for `text.html.ruby` and only "descramble" that specific scope, but it must have been changed along the way to do the opposite. I'll investigate further.

Comment (Arcanemagus) [inline lib/index.js]: If it's working properly _now_, I'm not really sure that's worth the effort, especially if this is the method that other packages use to deal with this issue.

Comment (ricardograca) [inline lib/index.js]: Ok, found an answer. The `language-ruby-on-rails` package isn't marking Rails ERB files as such, but just as regular ERB files. Until [this issue](https://github.com/atom/language-ruby-on-rails/issues/14) is fixed we have to leave `linter-erb` as is, otherwise we would be back in the situation where this package was raising errors on the rails syntax.

When that issue is fixed then, the string replacement introduced with this commit should be limited to only the `text.html.ruby` scope.
